export const MENS_PRODUCT_REQUEST_MADE = 'MENS_PRODUCT_REQUEST_MADE';

export const MENS_PRODUCT_REQUEST_SUCCESS = 'MENS_PRODUCT_REQUEST_SUCCESS';

export const MENS_PRODUCT_REQUEST_FAILURE = 'MENS_PRODUCT_REQUEST_FAILURE';
