export const WOMENS_PRODUCT_REQUEST = 'WOMENS_PRODUCT_REQUEST';

export const WOMENS_PRODUCT_SUCCESS = 'WOMENS_PRODUCT_SUCCESS';

export const WOMENS_PRODUCT_FAILURE = 'WOMENS_PRODUCT_FAILURE';

export const TOTAL_WOMENS_DATA = 'TOTAL_WOMENS_DATA';